GET localhost:7070/api/routes

### Create user
POST http://localhost:7070/api/auth/register

{
    "username": "admin",
    "password": "test123"
}
### Login
POST http://localhost:7070/api/auth/login

{
    "username": "admin",
    "password": "test123"
}
> {%
    client.global.set("token", response.body.token);
    client.log("Logging Bearer Token.");
    client.log("Bearer " + response.body.token);
    client.log("Username: " + response.body.username);
%}

### Populate data
POST localhost:7070/boardgames/api/populate/games/dev

### Get All Boardgames
GET localhost:7070/api/boardgames

### Search game by title
GET http://localhost:7070/api/games/search?title=Cathedral

### search movie based by category
GET http://localhost:7070/api/games/search?title=DragonMaster&category=Fantasy

### search movie based by title and category
GET http://localhost:7070/api/games/search/category?title=DragonMaster&Category=Fantasy

### alternative endpoint
POST localhost:7070/api/populate/games/dev

